export const TypesStore = {
  state: {
    LANGUAGE: `GLOBAL:LANGUAGE`,
    STUDENTS: `GLOBAL:STUDENTS`,
    PSTUDENTS: `GLOBAL:PSTUDENTS`
  },
  actions: {
    GET_STUDENTS: `GLOBAL:GET_STUDENTS`,
    POST_STUDENTS: `GLOBAL:POST_STUDENTS`
  },
  mutations: {
    SET_LANGUAGE: `GLOBAL:SET_LANGUAJE`,
    SET_STUDENTS: `GLOBAL:GET_STUDENTS`,
    SET_PSTUDENTS: `GLOBAL:POST_STUDENTS`
  }
};
